- type: job
  id: CaptainSyndicate
  name: job-name-captain-syndicate
  description: job-description-captain-syndicate
  playTimeTracker: JobCaptainSyndicate
  startingGear: PassengerGear
  icon: JobIconCaptain
  joinNotifyCrew: false
  supervisors: job-supervisors-everyone
  access:
  - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - Syndicate
